#!/usr/bin/env php
<?php
if (php_sapi_name() !== 'cli') {
    die("This file can only be loaded into a CLI Enviroment!");
}

foreach ([__DIR__ . '/../../../autoload.php', __DIR__ . '/../vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        chdir(dirname(dirname($file)));
        require $file;
        break;
    }
}

return new \Signalize\Service\Manager();